name: Symptom Analyzer Tests

on:
  push:
    branches:
      - main
    paths:
      - 'backend/config/config.py'
      - 'backend/models/**'
  
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock pytest-xdist
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          pytest backend/ml_pipeline/tests/test_symptom_analyzer.py \
                backend/ml_pipeline/tests/test_final_pipeline.py \
                backend/ml_pipeline/tests/test_bias_metrics.py \
                backend/ml_pipeline/tests/test_retrieval_validation.py \
                backend/ml_pipeline/tests/test_integrated_pipeline.py -v
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Notify on success
        if: success()
        run: echo "✅ ML Pipeline tests passed successfully!"


      - name: Notify on failure
        if: failure()
        run: echo "❌ ML Pipeline tests failed!"